# tasks/install.yml
---
- name: Update apt cache
  apt:
    update_cache: yes
  tags:
    - nginx
    - install

- name: Install Nginx
  apt:
    name: "{{ nginx_package_name }}"
    state: present
  tags:
    - nginx
    - install
